### ISSUE TITLE
Port 5000 already in use.

### ISSUE THREAD

**Issue by SuperKafu** [Ombi-app/Ombi.News#1]
Hi,

Just wanted to mention that in macOS Monterey, port 5000 is used by the Airplay Reciever.
Turning the feature off from Sharing options might help.
<img width="163" alt="image" src="https://user-images.githubusercontent.com/35775512/207428582-79110657-6c9c-43df-9e0b-3a7ed2b8eeab.png">

**Comment by tidusjar** [comment]
This is the wrong repo. You can change the port ombi runs on.  https://docs.ombi.app/info/startup-parameters/
